import Head from 'next/head'
import { DonutChart } from 'react-circle-chart'
import Base from '../components/Base'


export default function Home() {

  const expenseItems: {
    value: number,
    label: string,
    color?: string,
    displayValue?: string
  }[] =
    [
      {
        value: 25,
        label: 'Stocks'
      },
      {
        value: 5,
        label: 'Cash'
      },
      {
        value: 25,
        label: 'Crypto'
      }
    ]


  return (
    <>
      <Head>
        <title>Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Base headline="Welcome back!">
        <div className="flex">
          <div className="w-1/2 flex flex-col">
            <h2 className='w-full'>This month's expenses</h2>
            <DonutChart items={expenseItems} roundedCaps={false} size="sm" />
          </div>
          <div className="w-1/2 flex flex-col">
            <h2 className='w-full'>Critical budgets</h2>
            <div className="w-full flex flex-col">
              <div className="flex w-full mb-3">
                <div className="w-1/3 text-xl items-center flex">
                  Medien
                </div>
                <div className="w-2/3 bg-neutral-200 flex">
                  <div className="w-[86%] bg-red-600 text-white pl-2 py-1">
                    14€ of 17€ (86%)
                  </div>
                </div>
              </div>
              <div className="flex w-full">
                <div className="w-1/3 text-xl items-center flex">
                  Auto
                </div>
                <div className="w-2/3 bg-neutral-200 flex">
                  <div className="w-[74%] bg-yellow-500 text-white pl-2 py-1">
                    148€ of 200€ (74%)
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Base>
    </>
  )
}
